{{- if or .Values.auth.passwordAuth .Values.auth.groups }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.fileAuthSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
{{- if .Values.auth.passwordAuth }}
  password.db: {{ .Values.auth.passwordAuth.username }}:{{ (htpasswd .Values.auth.passwordAuth.username Values.auth.passwordAuth.password)| b64enc | quote }}
{{- end }}
{{- if .Values.auth.groups}}
  group.db: {{ .Values.auth.groups | b64enc }}
{{- end }}
{{- end }}
